version: '3.8'

services:
  localstack:
    image: localstack/localstack-pro
    environment:
      DEBUG: 1
      AWS_DEFAULT_REGION: us-east-1
      DOCKER_HOST: unix:///var/run/docker.sock
      LOCALSTACK_AUTH_TOKEN: "${LOCALSTACK_AUTH_TOKEN:-}"
    ports:
      - "4566:4566" # localstack gateway
      - "4510-4559:4510-4559" # external services port range
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"       
      - "/var/run/docker.sock:/var/run/docker.sock"       
      - './.localstack:/etc/localstack/init'       
      - "./ca-capitalone-256.crt:/etc/ssl/certs/ca-capitalone-256.crt"